auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/data/boltdb
    cache_location: /loki/data/cache
    cache_ttl: 24h

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

ruler:
  rule_path: /loki/rules
  alertmanager_url: http://localhost:9093
