auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      directory: /loki/data/chunks

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/data/chunks
  boltdb_shipper:
    active_index_directory: /loki/data/boltdb
    cache_location: /loki/data/cache
    shared_store: filesystem
    cache_ttl: 24h

limits_config:
  allow_structured_metadata: false  # <---- отключаем структурированные метаданные

ruler:
  rule_path: /loki/rules