auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/data/chunks
      rules_directory: /loki/rules
  replication_factor: 1

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/data/boltdb
    cache_location: /loki/data/cache
    cache_size_bytes: 5GB
    cache_ttl: 24h

limits_config:
  allow_structured_metadata: false

ruler:
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093