services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 13690:13690
    volumes:
      - .:/app/auth-service
    networks:
      - nats
    depends_on:
      nats:
        condition: service_started
      postgres-auth: 
        condition: service_healthy

  postgres-auth:
    image: postgres
    command: 
    - -p 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1789
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5434"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5434
    volumes:
      - postgres-auth-db:/var/lib/postgresql/data
    networks:
      - nats

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 13691:13691
    expose:
      - 13691
    volumes:
      - .:/app/notification-service
    networks:
      - nats
    depends_on:
      auth-service:
        condition: service_started
      device-management-service:
        condition: service_started
      nats:
        condition: service_started

  device-management-service:
    build:
      context: ./device-management-service
      dockerfile: Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 13692:13692
    volumes:
      - .:/app/device-management-service
    networks:
      - nats
    depends_on:
      auth-service:
       condition: service_started
      postgres-device-management:
        condition: service_healthy
      nats: 
        condition: service_started

  postgres-device-management:
    image: postgres
    command: 
    - -p 5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1789
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5435"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5435:5435
    volumes:
      - postgres-device-management-db:/var/lib/postgresql/data
    networks:
      - nats

  api-gateway-service:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 13693:13693
    expose:
      - 13693
    volumes:
      - .:/app/api-gateway-service
    networks:
      - nats
    depends_on:
      auth-service:
        condition: service_started
      device-management-service:
        condition: service_started
      nats:
        condition: service_started

  data-processing-service:
    build:
      context: ./data-processing-service
      dockerfile: Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 13694:13694
    volumes:
      - .:/app/data-processing-service
    networks:
      - nats
    depends_on:
      notification-service:
        condition: service_started
      nats:
        condition: service_started

  postgres-data-processing:
    image: postgres
    command: 
    - -p 5436
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1789
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5436"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5436
    volumes:
      - postgres-data-processing-db:/var/lib/postgresql/data
    networks:
      - nats

  data-ingestion-service:
    build:
      context: ./data-ingestion-service
      dockerfile: Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 10s
    ports:
      - 13695:13695
    expose:
      - 13695
    volumes:
      - .:/app/data-ingestion-service
    networks:
      - nats
    depends_on:
      device-management-service:
        condition: service_started
      nats:
        condition: service_started
      data-processing-service:
        condition: service_started

  nats:
    image: nats
    ports:
      - 4222:4222
    networks:
      - nats

volumes:
  postgres-auth-db:
  postgres-device-management-db:
  postgres-data-processing-db:


networks:
  nats:
    name: nats


  