FROM golang:1.23.0-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash openssh

WORKDIR /app

RUN mkdir -p /app/monitoring-system/data-ingestion-service
WORKDIR /app/monitoring-system/data-ingestion-service

COPY . .

RUN go mod download && go mod verify

RUN go build -o /bin/data-ingestion-service /app/monitoring-system/data-ingestion-service/cmd/main.go

EXPOSE 13695

CMD ["/bin/data-ingestion-service"]