FROM golang:1.23.0-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash openssh

WORKDIR /app

RUN mkdir -p /app/monitoring-system/notification-service
WORKDIR /app/monitoring-system/notification-service

COPY . .

RUN go mod download && go mod verify

RUN go build -o /bin/notification-service /app/monitoring-system/notification-service/cmd/main.go

EXPOSE 13691

CMD ["/bin/notification-service"]