FROM golang:1.23.0-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash openssh

WORKDIR /app

RUN mkdir -p /app/monitoring-system/api-gateway-service
WORKDIR /app/monitoring-system/api-gateway-service

COPY . .

RUN go mod download && go mod verify

RUN go build -o /bin/api-gateway-service /app/monitoring-system/api-gateway-service/cmd/main.go

EXPOSE 13693

CMD ["/bin/api-gateway-service"]