// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: sendnotify.proto

package pbsendnotify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      int32                  `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotifyReq) Reset() {
	*x = SendNotifyReq{}
	mi := &file_sendnotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotifyReq) ProtoMessage() {}

func (x *SendNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sendnotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotifyReq.ProtoReflect.Descriptor instead.
func (*SendNotifyReq) Descriptor() ([]byte, []int) {
	return file_sendnotify_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotifyReq) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *SendNotifyReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendNotifyReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var File_sendnotify_proto protoreflect.FileDescriptor

const file_sendnotify_proto_rawDesc = "" +
	"\n" +
	"\x10sendnotify.proto\x12\tpbmessage\"Y\n" +
	"\rSendNotifyReq\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\x05R\bDeviceID\x12\x12\n" +
	"\x04Text\x18\x02 \x01(\tR\x04Text\x12\x18\n" +
	"\aSubject\x18\x03 \x01(\tR\aSubjectB\x10Z\x0e.;pbsendnotifyb\x06proto3"

var (
	file_sendnotify_proto_rawDescOnce sync.Once
	file_sendnotify_proto_rawDescData []byte
)

func file_sendnotify_proto_rawDescGZIP() []byte {
	file_sendnotify_proto_rawDescOnce.Do(func() {
		file_sendnotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sendnotify_proto_rawDesc), len(file_sendnotify_proto_rawDesc)))
	})
	return file_sendnotify_proto_rawDescData
}

var file_sendnotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sendnotify_proto_goTypes = []any{
	(*SendNotifyReq)(nil), // 0: pbmessage.SendNotifyReq
}
var file_sendnotify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendnotify_proto_init() }
func file_sendnotify_proto_init() {
	if File_sendnotify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sendnotify_proto_rawDesc), len(file_sendnotify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sendnotify_proto_goTypes,
		DependencyIndexes: file_sendnotify_proto_depIdxs,
		MessageInfos:      file_sendnotify_proto_msgTypes,
	}.Build()
	File_sendnotify_proto = out.File
	file_sendnotify_proto_goTypes = nil
	file_sendnotify_proto_depIdxs = nil
}
