FROM golang:1.23.0-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash openssh

WORKDIR /app

RUN mkdir -p /app/monitoring-system/auth-service
WORKDIR /app/monitoring-system/auth-service

COPY . .

RUN go mod download && go mod verify

RUN go build -o /bin/auth-service /app/monitoring-system/auth-service/cmd/main.go

CMD ["/bin/auth-service"]