// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: messages.proto

package pbmessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageSave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceID      int32                  `protobuf:"varint,2,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=Component,proto3" json:"Component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSave) Reset() {
	*x = MessageSave{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSave) ProtoMessage() {}

func (x *MessageSave) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSave.ProtoReflect.Descriptor instead.
func (*MessageSave) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MessageSave) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MessageSave) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *MessageSave) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageSave) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessageSave) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type ReportGetAllByPeriodReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetAllByPeriodReq) Reset() {
	*x = ReportGetAllByPeriodReq{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetAllByPeriodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetAllByPeriodReq) ProtoMessage() {}

func (x *ReportGetAllByPeriodReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetAllByPeriodReq.ProtoReflect.Descriptor instead.
func (*ReportGetAllByPeriodReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ReportGetAllByPeriodReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ReportGetAllByPeriodReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ReportGetAllByPeriod struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceID       int32                  `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeviceType     string                 `protobuf:"bytes,3,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Address        string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Responsible    []int32                `protobuf:"varint,5,rep,packed,name=Responsible,proto3" json:"Responsible,omitempty"`
	GotAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=GotAt,proto3" json:"GotAt,omitempty"`
	Message        string                 `protobuf:"bytes,7,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageType    string                 `protobuf:"bytes,8,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ServinityLevel string                 `protobuf:"bytes,9,opt,name=ServinityLevel,proto3" json:"ServinityLevel,omitempty"`
	Component      string                 `protobuf:"bytes,10,opt,name=Component,proto3" json:"Component,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportGetAllByPeriod) Reset() {
	*x = ReportGetAllByPeriod{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetAllByPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetAllByPeriod) ProtoMessage() {}

func (x *ReportGetAllByPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetAllByPeriod.ProtoReflect.Descriptor instead.
func (*ReportGetAllByPeriod) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ReportGetAllByPeriod) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *ReportGetAllByPeriod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportGetAllByPeriod) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *ReportGetAllByPeriod) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReportGetAllByPeriod) GetResponsible() []int32 {
	if x != nil {
		return x.Responsible
	}
	return nil
}

func (x *ReportGetAllByPeriod) GetGotAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GotAt
	}
	return nil
}

func (x *ReportGetAllByPeriod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportGetAllByPeriod) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ReportGetAllByPeriod) GetServinityLevel() string {
	if x != nil {
		return x.ServinityLevel
	}
	return ""
}

func (x *ReportGetAllByPeriod) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type ReportGetAllByPeriodResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Report        []*ReportGetAllByPeriod `protobuf:"bytes,1,rep,name=Report,proto3" json:"Report,omitempty"`
	Error         string                  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetAllByPeriodResp) Reset() {
	*x = ReportGetAllByPeriodResp{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetAllByPeriodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetAllByPeriodResp) ProtoMessage() {}

func (x *ReportGetAllByPeriodResp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetAllByPeriodResp.ProtoReflect.Descriptor instead.
func (*ReportGetAllByPeriodResp) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ReportGetAllByPeriodResp) GetReport() []*ReportGetAllByPeriod {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ReportGetAllByPeriodResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportGetAllByDeviceIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetAllByDeviceIdReq) Reset() {
	*x = ReportGetAllByDeviceIdReq{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetAllByDeviceIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetAllByDeviceIdReq) ProtoMessage() {}

func (x *ReportGetAllByDeviceIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetAllByDeviceIdReq.ProtoReflect.Descriptor instead.
func (*ReportGetAllByDeviceIdReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ReportGetAllByDeviceIdReq) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type ReportGetAllByDeviceId struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceID       int32                  `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeviceType     string                 `protobuf:"bytes,3,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Address        string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Responsible    []int32                `protobuf:"varint,5,rep,packed,name=Responsible,proto3" json:"Responsible,omitempty"`
	GotAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=GotAt,proto3" json:"GotAt,omitempty"`
	Message        string                 `protobuf:"bytes,7,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageType    string                 `protobuf:"bytes,8,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ServinityLevel string                 `protobuf:"bytes,9,opt,name=ServinityLevel,proto3" json:"ServinityLevel,omitempty"`
	Component      string                 `protobuf:"bytes,10,opt,name=Component,proto3" json:"Component,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportGetAllByDeviceId) Reset() {
	*x = ReportGetAllByDeviceId{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetAllByDeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetAllByDeviceId) ProtoMessage() {}

func (x *ReportGetAllByDeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetAllByDeviceId.ProtoReflect.Descriptor instead.
func (*ReportGetAllByDeviceId) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ReportGetAllByDeviceId) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *ReportGetAllByDeviceId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportGetAllByDeviceId) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *ReportGetAllByDeviceId) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReportGetAllByDeviceId) GetResponsible() []int32 {
	if x != nil {
		return x.Responsible
	}
	return nil
}

func (x *ReportGetAllByDeviceId) GetGotAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GotAt
	}
	return nil
}

func (x *ReportGetAllByDeviceId) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportGetAllByDeviceId) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ReportGetAllByDeviceId) GetServinityLevel() string {
	if x != nil {
		return x.ServinityLevel
	}
	return ""
}

func (x *ReportGetAllByDeviceId) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type ReportGetAllByDeviceIdResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Report        []*ReportGetAllByDeviceId `protobuf:"bytes,1,rep,name=Report,proto3" json:"Report,omitempty"`
	Error         string                    `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetAllByDeviceIdResp) Reset() {
	*x = ReportGetAllByDeviceIdResp{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetAllByDeviceIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetAllByDeviceIdResp) ProtoMessage() {}

func (x *ReportGetAllByDeviceIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetAllByDeviceIdResp.ProtoReflect.Descriptor instead.
func (*ReportGetAllByDeviceIdResp) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReportGetAllByDeviceIdResp) GetReport() []*ReportGetAllByDeviceId {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ReportGetAllByDeviceIdResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportGetCountByMessageTypeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetCountByMessageTypeReq) Reset() {
	*x = ReportGetCountByMessageTypeReq{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetCountByMessageTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetCountByMessageTypeReq) ProtoMessage() {}

func (x *ReportGetCountByMessageTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetCountByMessageTypeReq.ProtoReflect.Descriptor instead.
func (*ReportGetCountByMessageTypeReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ReportGetCountByMessageTypeReq) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

type ReportGetCountByMessageType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      int32                  `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Responsible   []int32                `protobuf:"varint,5,rep,packed,name=Responsible,proto3" json:"Responsible,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetCountByMessageType) Reset() {
	*x = ReportGetCountByMessageType{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetCountByMessageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetCountByMessageType) ProtoMessage() {}

func (x *ReportGetCountByMessageType) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetCountByMessageType.ProtoReflect.Descriptor instead.
func (*ReportGetCountByMessageType) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ReportGetCountByMessageType) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *ReportGetCountByMessageType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportGetCountByMessageType) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *ReportGetCountByMessageType) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReportGetCountByMessageType) GetResponsible() []int32 {
	if x != nil {
		return x.Responsible
	}
	return nil
}

func (x *ReportGetCountByMessageType) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReportGetCountByMessageTypeResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Report        []*ReportGetCountByMessageType `protobuf:"bytes,1,rep,name=Report,proto3" json:"Report,omitempty"`
	Error         string                         `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportGetCountByMessageTypeResp) Reset() {
	*x = ReportGetCountByMessageTypeResp{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGetCountByMessageTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGetCountByMessageTypeResp) ProtoMessage() {}

func (x *ReportGetCountByMessageTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGetCountByMessageTypeResp.ProtoReflect.Descriptor instead.
func (*ReportGetCountByMessageTypeResp) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ReportGetCountByMessageTypeResp) GetReport() []*ReportGetCountByMessageType {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ReportGetCountByMessageTypeResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MonthReportRow struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeviceId            int32                  `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	MessageType         string                 `protobuf:"bytes,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ActiveDays          int32                  `protobuf:"varint,3,opt,name=ActiveDays,proto3" json:"ActiveDays,omitempty"`
	TotalMessages       int64                  `protobuf:"varint,4,opt,name=TotalMessages,proto3" json:"TotalMessages,omitempty"`
	AvgDailyMessages    float64                `protobuf:"fixed64,5,opt,name=AvgDailyMessages,proto3" json:"AvgDailyMessages,omitempty"`
	MaxDailyMessages    int64                  `protobuf:"varint,6,opt,name=MaxDailyMessages,proto3" json:"MaxDailyMessages,omitempty"`
	MedianDailyMessages float64                `protobuf:"fixed64,7,opt,name=MedianDailyMessages,proto3" json:"MedianDailyMessages,omitempty"`
	TotalCritical       int64                  `protobuf:"varint,8,opt,name=TotalCritical,proto3" json:"TotalCritical,omitempty"`
	MaxDailyCritical    int64                  `protobuf:"varint,9,opt,name=MaxDailyCritical,proto3" json:"MaxDailyCritical,omitempty"`
	MaxDailyComponents  int32                  `protobuf:"varint,10,opt,name=MaxDailyComponents,proto3" json:"MaxDailyComponents,omitempty"`
	MostActiveComponent string                 `protobuf:"bytes,11,opt,name=MostActiveComponent,proto3" json:"MostActiveComponent,omitempty"`
	FirstCriticalTime   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=FirstCriticalTime,proto3" json:"FirstCriticalTime,omitempty"`
	LastCriticalTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=LastCriticalTime,proto3" json:"LastCriticalTime,omitempty"`
	AvgCriticalInterval float64                `protobuf:"fixed64,14,opt,name=AvgCriticalInterval,proto3" json:"AvgCriticalInterval,omitempty"`
	CriticalPercentage  float64                `protobuf:"fixed64,15,opt,name=CriticalPercentage,proto3" json:"CriticalPercentage,omitempty"`
	OverallVolumeRank   int32                  `protobuf:"varint,16,opt,name=OverallVolumeRank,proto3" json:"OverallVolumeRank,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MonthReportRow) Reset() {
	*x = MonthReportRow{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthReportRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthReportRow) ProtoMessage() {}

func (x *MonthReportRow) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthReportRow.ProtoReflect.Descriptor instead.
func (*MonthReportRow) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MonthReportRow) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *MonthReportRow) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MonthReportRow) GetActiveDays() int32 {
	if x != nil {
		return x.ActiveDays
	}
	return 0
}

func (x *MonthReportRow) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *MonthReportRow) GetAvgDailyMessages() float64 {
	if x != nil {
		return x.AvgDailyMessages
	}
	return 0
}

func (x *MonthReportRow) GetMaxDailyMessages() int64 {
	if x != nil {
		return x.MaxDailyMessages
	}
	return 0
}

func (x *MonthReportRow) GetMedianDailyMessages() float64 {
	if x != nil {
		return x.MedianDailyMessages
	}
	return 0
}

func (x *MonthReportRow) GetTotalCritical() int64 {
	if x != nil {
		return x.TotalCritical
	}
	return 0
}

func (x *MonthReportRow) GetMaxDailyCritical() int64 {
	if x != nil {
		return x.MaxDailyCritical
	}
	return 0
}

func (x *MonthReportRow) GetMaxDailyComponents() int32 {
	if x != nil {
		return x.MaxDailyComponents
	}
	return 0
}

func (x *MonthReportRow) GetMostActiveComponent() string {
	if x != nil {
		return x.MostActiveComponent
	}
	return ""
}

func (x *MonthReportRow) GetFirstCriticalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstCriticalTime
	}
	return nil
}

func (x *MonthReportRow) GetLastCriticalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCriticalTime
	}
	return nil
}

func (x *MonthReportRow) GetAvgCriticalInterval() float64 {
	if x != nil {
		return x.AvgCriticalInterval
	}
	return 0
}

func (x *MonthReportRow) GetCriticalPercentage() float64 {
	if x != nil {
		return x.CriticalPercentage
	}
	return 0
}

func (x *MonthReportRow) GetOverallVolumeRank() int32 {
	if x != nil {
		return x.OverallVolumeRank
	}
	return 0
}

type MonthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonthReport   []*MonthReportRow      `protobuf:"bytes,1,rep,name=MonthReport,proto3" json:"MonthReport,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthReport) Reset() {
	*x = MonthReport{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthReport) ProtoMessage() {}

func (x *MonthReport) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthReport.ProtoReflect.Descriptor instead.
func (*MonthReport) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *MonthReport) GetMonthReport() []*MonthReportRow {
	if x != nil {
		return x.MonthReport
	}
	return nil
}

func (x *MonthReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\n" +
	"pbmessages\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\vMessageSave\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1a\n" +
	"\bDeviceID\x18\x02 \x01(\x05R\bDeviceID\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12 \n" +
	"\vMessageType\x18\x04 \x01(\tR\vMessageType\x12\x1c\n" +
	"\tComponent\x18\x05 \x01(\tR\tComponent\"\x89\x01\n" +
	"\x17ReportGetAllByPeriodReq\x128\n" +
	"\tStartTime\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tStartTime\x124\n" +
	"\aEndTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aEndTime\"\xd6\x02\n" +
	"\x14ReportGetAllByPeriod\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\x05R\bDeviceID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"DeviceType\x18\x03 \x01(\tR\n" +
	"DeviceType\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12 \n" +
	"\vResponsible\x18\x05 \x03(\x05R\vResponsible\x120\n" +
	"\x05GotAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05GotAt\x12\x18\n" +
	"\aMessage\x18\a \x01(\tR\aMessage\x12 \n" +
	"\vMessageType\x18\b \x01(\tR\vMessageType\x12&\n" +
	"\x0eServinityLevel\x18\t \x01(\tR\x0eServinityLevel\x12\x1c\n" +
	"\tComponent\x18\n" +
	" \x01(\tR\tComponent\"j\n" +
	"\x18ReportGetAllByPeriodResp\x128\n" +
	"\x06Report\x18\x01 \x03(\v2 .pbmessages.ReportGetAllByPeriodR\x06Report\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"7\n" +
	"\x19ReportGetAllByDeviceIdReq\x12\x1a\n" +
	"\bDeviceId\x18\x01 \x01(\x05R\bDeviceId\"\xd8\x02\n" +
	"\x16ReportGetAllByDeviceId\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\x05R\bDeviceID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"DeviceType\x18\x03 \x01(\tR\n" +
	"DeviceType\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12 \n" +
	"\vResponsible\x18\x05 \x03(\x05R\vResponsible\x120\n" +
	"\x05GotAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05GotAt\x12\x18\n" +
	"\aMessage\x18\a \x01(\tR\aMessage\x12 \n" +
	"\vMessageType\x18\b \x01(\tR\vMessageType\x12&\n" +
	"\x0eServinityLevel\x18\t \x01(\tR\x0eServinityLevel\x12\x1c\n" +
	"\tComponent\x18\n" +
	" \x01(\tR\tComponent\"n\n" +
	"\x1aReportGetAllByDeviceIdResp\x12:\n" +
	"\x06Report\x18\x01 \x03(\v2\".pbmessages.ReportGetAllByDeviceIdR\x06Report\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"B\n" +
	"\x1eReportGetCountByMessageTypeReq\x12 \n" +
	"\vMessageType\x18\x01 \x01(\tR\vMessageType\"\xbf\x01\n" +
	"\x1bReportGetCountByMessageType\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\x05R\bDeviceID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"DeviceType\x18\x03 \x01(\tR\n" +
	"DeviceType\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12 \n" +
	"\vResponsible\x18\x05 \x03(\x05R\vResponsible\x12\x14\n" +
	"\x05Count\x18\x06 \x01(\x05R\x05Count\"x\n" +
	"\x1fReportGetCountByMessageTypeResp\x12?\n" +
	"\x06Report\x18\x01 \x03(\v2'.pbmessages.ReportGetCountByMessageTypeR\x06Report\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"\xf4\x05\n" +
	"\x0eMonthReportRow\x12\x1a\n" +
	"\bDeviceId\x18\x01 \x01(\x05R\bDeviceId\x12 \n" +
	"\vMessageType\x18\x02 \x01(\tR\vMessageType\x12\x1e\n" +
	"\n" +
	"ActiveDays\x18\x03 \x01(\x05R\n" +
	"ActiveDays\x12$\n" +
	"\rTotalMessages\x18\x04 \x01(\x03R\rTotalMessages\x12*\n" +
	"\x10AvgDailyMessages\x18\x05 \x01(\x01R\x10AvgDailyMessages\x12*\n" +
	"\x10MaxDailyMessages\x18\x06 \x01(\x03R\x10MaxDailyMessages\x120\n" +
	"\x13MedianDailyMessages\x18\a \x01(\x01R\x13MedianDailyMessages\x12$\n" +
	"\rTotalCritical\x18\b \x01(\x03R\rTotalCritical\x12*\n" +
	"\x10MaxDailyCritical\x18\t \x01(\x03R\x10MaxDailyCritical\x12.\n" +
	"\x12MaxDailyComponents\x18\n" +
	" \x01(\x05R\x12MaxDailyComponents\x120\n" +
	"\x13MostActiveComponent\x18\v \x01(\tR\x13MostActiveComponent\x12H\n" +
	"\x11FirstCriticalTime\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x11FirstCriticalTime\x12F\n" +
	"\x10LastCriticalTime\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x10LastCriticalTime\x120\n" +
	"\x13AvgCriticalInterval\x18\x0e \x01(\x01R\x13AvgCriticalInterval\x12.\n" +
	"\x12CriticalPercentage\x18\x0f \x01(\x01R\x12CriticalPercentage\x12,\n" +
	"\x11OverallVolumeRank\x18\x10 \x01(\x05R\x11OverallVolumeRank\"a\n" +
	"\vMonthReport\x12<\n" +
	"\vMonthReport\x18\x01 \x03(\v2\x1a.pbmessages.MonthReportRowR\vMonthReport\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05ErrorB\x0eZ\f.;pbmessagesb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_messages_proto_goTypes = []any{
	(*MessageSave)(nil),                     // 0: pbmessages.MessageSave
	(*ReportGetAllByPeriodReq)(nil),         // 1: pbmessages.ReportGetAllByPeriodReq
	(*ReportGetAllByPeriod)(nil),            // 2: pbmessages.ReportGetAllByPeriod
	(*ReportGetAllByPeriodResp)(nil),        // 3: pbmessages.ReportGetAllByPeriodResp
	(*ReportGetAllByDeviceIdReq)(nil),       // 4: pbmessages.ReportGetAllByDeviceIdReq
	(*ReportGetAllByDeviceId)(nil),          // 5: pbmessages.ReportGetAllByDeviceId
	(*ReportGetAllByDeviceIdResp)(nil),      // 6: pbmessages.ReportGetAllByDeviceIdResp
	(*ReportGetCountByMessageTypeReq)(nil),  // 7: pbmessages.ReportGetCountByMessageTypeReq
	(*ReportGetCountByMessageType)(nil),     // 8: pbmessages.ReportGetCountByMessageType
	(*ReportGetCountByMessageTypeResp)(nil), // 9: pbmessages.ReportGetCountByMessageTypeResp
	(*MonthReportRow)(nil),                  // 10: pbmessages.MonthReportRow
	(*MonthReport)(nil),                     // 11: pbmessages.MonthReport
	(*timestamppb.Timestamp)(nil),           // 12: google.protobuf.Timestamp
}
var file_messages_proto_depIdxs = []int32{
	12, // 0: pbmessages.ReportGetAllByPeriodReq.StartTime:type_name -> google.protobuf.Timestamp
	12, // 1: pbmessages.ReportGetAllByPeriodReq.EndTime:type_name -> google.protobuf.Timestamp
	12, // 2: pbmessages.ReportGetAllByPeriod.GotAt:type_name -> google.protobuf.Timestamp
	2,  // 3: pbmessages.ReportGetAllByPeriodResp.Report:type_name -> pbmessages.ReportGetAllByPeriod
	12, // 4: pbmessages.ReportGetAllByDeviceId.GotAt:type_name -> google.protobuf.Timestamp
	5,  // 5: pbmessages.ReportGetAllByDeviceIdResp.Report:type_name -> pbmessages.ReportGetAllByDeviceId
	8,  // 6: pbmessages.ReportGetCountByMessageTypeResp.Report:type_name -> pbmessages.ReportGetCountByMessageType
	12, // 7: pbmessages.MonthReportRow.FirstCriticalTime:type_name -> google.protobuf.Timestamp
	12, // 8: pbmessages.MonthReportRow.LastCriticalTime:type_name -> google.protobuf.Timestamp
	10, // 9: pbmessages.MonthReport.MonthReport:type_name -> pbmessages.MonthReportRow
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
