// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: apidevices.proto

package pbapidevices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Responsible   []int32                `protobuf:"varint,5,rep,packed,name=Responsible,proto3" json:"Responsible,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_apidevices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetResponsible() []int32 {
	if x != nil {
		return x.Responsible
	}
	return nil
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_apidevices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReq) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type CreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       *Device                `protobuf:"bytes,1,opt,name=Created,proto3" json:"Created,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_apidevices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResp) GetCreated() *Device {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *CreateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResp) Reset() {
	*x = ReadResp{}
	mi := &file_apidevices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResp) ProtoMessage() {}

func (x *ReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResp.ProtoReflect.Descriptor instead.
func (*ReadResp) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResp) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ReadResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_apidevices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReq) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResp) Reset() {
	*x = UpdateResp{}
	mi := &file_apidevices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResp) ProtoMessage() {}

func (x *UpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResp.ProtoReflect.Descriptor instead.
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_apidevices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReq) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_apidevices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_apidevices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_apidevices_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apidevices_proto protoreflect.FileDescriptor

const file_apidevices_proto_rawDesc = "" +
	"\n" +
	"\x10apidevices.proto\x12\tpbdevices\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"DeviceType\x18\x03 \x01(\tR\n" +
	"DeviceType\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12 \n" +
	"\vResponsible\x18\x05 \x03(\x05R\vResponsible\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\"6\n" +
	"\tCreateReq\x12)\n" +
	"\x06Device\x18\x01 \x01(\v2\x11.pbdevices.DeviceR\x06Device\"O\n" +
	"\n" +
	"CreateResp\x12+\n" +
	"\aCreated\x18\x01 \x01(\v2\x11.pbdevices.DeviceR\aCreated\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"M\n" +
	"\bReadResp\x12+\n" +
	"\aDevices\x18\x01 \x03(\v2\x11.pbdevices.DeviceR\aDevices\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"6\n" +
	"\tUpdateReq\x12)\n" +
	"\x06Device\x18\x01 \x01(\v2\x11.pbdevices.DeviceR\x06Device\"\"\n" +
	"\n" +
	"UpdateResp\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\"\x1b\n" +
	"\tDeleteReq\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\"\"\n" +
	"\n" +
	"DeleteResp\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05ErrorB\x10Z\x0e.;pbapidevicesb\x06proto3"

var (
	file_apidevices_proto_rawDescOnce sync.Once
	file_apidevices_proto_rawDescData []byte
)

func file_apidevices_proto_rawDescGZIP() []byte {
	file_apidevices_proto_rawDescOnce.Do(func() {
		file_apidevices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apidevices_proto_rawDesc), len(file_apidevices_proto_rawDesc)))
	})
	return file_apidevices_proto_rawDescData
}

var file_apidevices_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_apidevices_proto_goTypes = []any{
	(*Device)(nil),                // 0: pbdevices.Device
	(*CreateReq)(nil),             // 1: pbdevices.CreateReq
	(*CreateResp)(nil),            // 2: pbdevices.CreateResp
	(*ReadResp)(nil),              // 3: pbdevices.ReadResp
	(*UpdateReq)(nil),             // 4: pbdevices.UpdateReq
	(*UpdateResp)(nil),            // 5: pbdevices.UpdateResp
	(*DeleteReq)(nil),             // 6: pbdevices.DeleteReq
	(*DeleteResp)(nil),            // 7: pbdevices.DeleteResp
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_apidevices_proto_depIdxs = []int32{
	8, // 0: pbdevices.Device.CreatedAt:type_name -> google.protobuf.Timestamp
	8, // 1: pbdevices.Device.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: pbdevices.CreateReq.Device:type_name -> pbdevices.Device
	0, // 3: pbdevices.CreateResp.Created:type_name -> pbdevices.Device
	0, // 4: pbdevices.ReadResp.Devices:type_name -> pbdevices.Device
	0, // 5: pbdevices.UpdateReq.Device:type_name -> pbdevices.Device
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apidevices_proto_init() }
func file_apidevices_proto_init() {
	if File_apidevices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apidevices_proto_rawDesc), len(file_apidevices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apidevices_proto_goTypes,
		DependencyIndexes: file_apidevices_proto_depIdxs,
		MessageInfos:      file_apidevices_proto_msgTypes,
	}.Build()
	File_apidevices_proto = out.File
	file_apidevices_proto_goTypes = nil
	file_apidevices_proto_depIdxs = nil
}
