// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: getmail.proto

package pbgetmail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        []int32                `protobuf:"varint,1,rep,packed,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailReq) Reset() {
	*x = GetEmailReq{}
	mi := &file_getmail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailReq) ProtoMessage() {}

func (x *GetEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_getmail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailReq.ProtoReflect.Descriptor instead.
func (*GetEmailReq) Descriptor() ([]byte, []int) {
	return file_getmail_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmailReq) GetUserID() []int32 {
	if x != nil {
		return x.UserID
	}
	return nil
}

type GetEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         []string               `protobuf:"bytes,1,rep,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailResp) Reset() {
	*x = GetEmailResp{}
	mi := &file_getmail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailResp) ProtoMessage() {}

func (x *GetEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_getmail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailResp.ProtoReflect.Descriptor instead.
func (*GetEmailResp) Descriptor() ([]byte, []int) {
	return file_getmail_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmailResp) GetEmail() []string {
	if x != nil {
		return x.Email
	}
	return nil
}

var File_getmail_proto protoreflect.FileDescriptor

const file_getmail_proto_rawDesc = "" +
	"\n" +
	"\rgetmail.proto\x12\tpbmessage\"%\n" +
	"\vGetEmailReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x03(\x05R\x06UserID\"$\n" +
	"\fGetEmailResp\x12\x14\n" +
	"\x05Email\x18\x01 \x03(\tR\x05EmailB\rZ\v.;pbgetmailb\x06proto3"

var (
	file_getmail_proto_rawDescOnce sync.Once
	file_getmail_proto_rawDescData []byte
)

func file_getmail_proto_rawDescGZIP() []byte {
	file_getmail_proto_rawDescOnce.Do(func() {
		file_getmail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getmail_proto_rawDesc), len(file_getmail_proto_rawDesc)))
	})
	return file_getmail_proto_rawDescData
}

var file_getmail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getmail_proto_goTypes = []any{
	(*GetEmailReq)(nil),  // 0: pbmessage.GetEmailReq
	(*GetEmailResp)(nil), // 1: pbmessage.GetEmailResp
}
var file_getmail_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getmail_proto_init() }
func file_getmail_proto_init() {
	if File_getmail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getmail_proto_rawDesc), len(file_getmail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_getmail_proto_goTypes,
		DependencyIndexes: file_getmail_proto_depIdxs,
		MessageInfos:      file_getmail_proto_msgTypes,
	}.Build()
	File_getmail_proto = out.File
	file_getmail_proto_goTypes = nil
	file_getmail_proto_depIdxs = nil
}
