// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: apitags.proto

package pbtags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeviceID       int32                  `protobuf:"varint,3,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Regexp         string                 `protobuf:"bytes,4,opt,name=Regexp,proto3" json:"Regexp,omitempty"`
	CompareType    string                 `protobuf:"bytes,5,opt,name=CompareType,proto3" json:"CompareType,omitempty"`
	Value          string                 `protobuf:"bytes,6,opt,name=Value,proto3" json:"Value,omitempty"`
	ArrayIndex     int32                  `protobuf:"varint,7,opt,name=ArrayIndex,proto3" json:"ArrayIndex,omitempty"`
	Subject        string                 `protobuf:"bytes,8,opt,name=Subject,proto3" json:"Subject,omitempty"`
	ServinityLevel string                 `protobuf:"bytes,9,opt,name=ServinityLevel,proto3" json:"ServinityLevel,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_apitags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDeviceID() int32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *Tag) GetRegexp() string {
	if x != nil {
		return x.Regexp
	}
	return ""
}

func (x *Tag) GetCompareType() string {
	if x != nil {
		return x.CompareType
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Tag) GetArrayIndex() int32 {
	if x != nil {
		return x.ArrayIndex
	}
	return 0
}

func (x *Tag) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Tag) GetServinityLevel() string {
	if x != nil {
		return x.ServinityLevel
	}
	return ""
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_apitags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReq) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type CreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       *Tag                   `protobuf:"bytes,1,opt,name=Created,proto3" json:"Created,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_apitags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResp) GetCreated() *Tag {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *CreateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResp) Reset() {
	*x = ReadResp{}
	mi := &file_apitags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResp) ProtoMessage() {}

func (x *ReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResp.ProtoReflect.Descriptor instead.
func (*ReadResp) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResp) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReadResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_apitags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReq) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type UpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResp) Reset() {
	*x = UpdateResp{}
	mi := &file_apitags_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResp) ProtoMessage() {}

func (x *UpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResp.ProtoReflect.Descriptor instead.
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_apitags_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReq) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_apitags_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_apitags_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_apitags_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apitags_proto protoreflect.FileDescriptor

const file_apitags_proto_rawDesc = "" +
	"\n" +
	"\rapitags.proto\x12\x06pbtags\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x02\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bDeviceID\x18\x03 \x01(\x05R\bDeviceID\x12\x16\n" +
	"\x06Regexp\x18\x04 \x01(\tR\x06Regexp\x12 \n" +
	"\vCompareType\x18\x05 \x01(\tR\vCompareType\x12\x14\n" +
	"\x05Value\x18\x06 \x01(\tR\x05Value\x12\x1e\n" +
	"\n" +
	"ArrayIndex\x18\a \x01(\x05R\n" +
	"ArrayIndex\x12\x18\n" +
	"\aSubject\x18\b \x01(\tR\aSubject\x12&\n" +
	"\x0eServinityLevel\x18\t \x01(\tR\x0eServinityLevel\x128\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\"*\n" +
	"\tCreateReq\x12\x1d\n" +
	"\x03Tag\x18\x01 \x01(\v2\v.pbtags.TagR\x03Tag\"I\n" +
	"\n" +
	"CreateResp\x12%\n" +
	"\aCreated\x18\x01 \x01(\v2\v.pbtags.TagR\aCreated\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"A\n" +
	"\bReadResp\x12\x1f\n" +
	"\x04Tags\x18\x01 \x03(\v2\v.pbtags.TagR\x04Tags\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"*\n" +
	"\tUpdateReq\x12\x1d\n" +
	"\x03Tag\x18\x01 \x01(\v2\v.pbtags.TagR\x03Tag\"\"\n" +
	"\n" +
	"UpdateResp\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\"\x1b\n" +
	"\tDeleteReq\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\"\"\n" +
	"\n" +
	"DeleteResp\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05ErrorB\n" +
	"Z\b.;pbtagsb\x06proto3"

var (
	file_apitags_proto_rawDescOnce sync.Once
	file_apitags_proto_rawDescData []byte
)

func file_apitags_proto_rawDescGZIP() []byte {
	file_apitags_proto_rawDescOnce.Do(func() {
		file_apitags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apitags_proto_rawDesc), len(file_apitags_proto_rawDesc)))
	})
	return file_apitags_proto_rawDescData
}

var file_apitags_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_apitags_proto_goTypes = []any{
	(*Tag)(nil),                   // 0: pbtags.Tag
	(*CreateReq)(nil),             // 1: pbtags.CreateReq
	(*CreateResp)(nil),            // 2: pbtags.CreateResp
	(*ReadResp)(nil),              // 3: pbtags.ReadResp
	(*UpdateReq)(nil),             // 4: pbtags.UpdateReq
	(*UpdateResp)(nil),            // 5: pbtags.UpdateResp
	(*DeleteReq)(nil),             // 6: pbtags.DeleteReq
	(*DeleteResp)(nil),            // 7: pbtags.DeleteResp
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_apitags_proto_depIdxs = []int32{
	8, // 0: pbtags.Tag.CreatedAt:type_name -> google.protobuf.Timestamp
	8, // 1: pbtags.Tag.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: pbtags.CreateReq.Tag:type_name -> pbtags.Tag
	0, // 3: pbtags.CreateResp.Created:type_name -> pbtags.Tag
	0, // 4: pbtags.ReadResp.Tags:type_name -> pbtags.Tag
	0, // 5: pbtags.UpdateReq.Tag:type_name -> pbtags.Tag
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apitags_proto_init() }
func file_apitags_proto_init() {
	if File_apitags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apitags_proto_rawDesc), len(file_apitags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apitags_proto_goTypes,
		DependencyIndexes: file_apitags_proto_depIdxs,
		MessageInfos:      file_apitags_proto_msgTypes,
	}.Build()
	File_apitags_proto = out.File
	file_apitags_proto_goTypes = nil
	file_apitags_proto_depIdxs = nil
}
